"""
Orchestrator State Definition Module

This module defines the strictly typed global memory dictionary (`AgentState`) 
used by the LangGraph orchestrator. It acts as the shared "whiteboard" that all 
independent agents read from and mutate during a single chat execution cycle.
"""
from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    """
    The shared state architecture of the conversation graph.
    All agents read from and mutate this specific state structure.
    Using `TypedDict` prevents runtime framework crashes (`UnboundLocalError`) 
    by enforcing rigid key existence from the moment the graph boots up.
    """
    # -------------------------------------------------------------------------
    # System Inputs
    # -------------------------------------------------------------------------
    query: str                          # The initial raw user query (combined with any Multimodal sub-text)
    chat_history: List[Dict[str, str]]  # Serialized previous conversation turns. Format: [{"role": "user", "content": "..."}, ...]
    
    # -------------------------------------------------------------------------
    # Routing & Context Flags
    # -------------------------------------------------------------------------
    intent: Optional[str]               # The classified action path generated by the Supervisor (e.g., "smalltalk", "rag", "analytical")
    search_query: Optional[str]         # The heavily AI-rewritten query optimized strictly for Vector Database matching
    context_chunks: List[Dict[str, Any]]# The raw dictionary payload snippets retrieved directly from the DB
    context_text: str                   # The formatted, merged, human-readable string of the aggregated context constraints
    
    # -------------------------------------------------------------------------
    # System Outputs
    # -------------------------------------------------------------------------
    answer: str                         # The final text synthesized by the dynamically assigned leaf agent
    sources: List[Dict[str, Any]]       # The filtered list of source metadata actively cited and returned to the frontend UI
    
    # -------------------------------------------------------------------------
    # Traceability & Enterprise Telemetry
    # -------------------------------------------------------------------------
    confidence: float                   # The mathematical accuracy/relevance similarity score of the chunks
    verifier_verdict: str               # Output from the independent hallucination verification checker (SUPPORTED/HALLUCINATION/ERROR)
    is_hallucinated: bool               # Explicit boolean flag signalling if the agent's logic drifted from retrieved facts
    optimizations: Dict[str, Any]       # Telemetry dictionary containing deep execution paths (e.g., specific agent used, dynamic temperature)
    
    # -------------------------------------------------------------------------
    # Internal Pipeline State Mechanics
    # -------------------------------------------------------------------------
    current_agent: Optional[str]        # Tracking string indicating which graph actor currently holds the execution token
    streaming_callback: Optional[Any]   # A pointer mapping to the Streamlit UI memory pipe allowing real-time async character yielding
